AppTwo/urls.py
from django.conf.urls import url
from django.urls import path
from AppTwo import views

#TEMPLATE TAGGING

app_name = 'AppTwo'

# urlpatterns = [
#     path('', views.help, name='help'),
# ]
urlpatterns = [
    path('register', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
    # path('relative', views.relative, name='relative'),
]

ProTwo/urls.py
from django.contrib import admin
from django.urls import path
from AppTwo import views
from django.conf.urls import url, include

# urlpatterns = [
#     path('help/', include ('AppTwo.urls')),
#     path('', views.help, name='help'),
#     path('admin/', admin.site.urls),
# ]

urlpatterns = [
    path('AppTwo/', include ('AppTwo.urls')),
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special')
    # path('formpage/', views.form_name_view, name='form_name')
]

# urlpatterns = [
#     path('users/', include ('AppTwo.urls')),
#     path('', views.index, name='index'),
#     path('admin/', admin.site.urls),
#     # path('formpage/', views.form_name_view, name='form_name')
# ]

AppTwo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# class User(models.Model):
#     first_name = models.CharField(max_length=128)
#     last_name = models.CharField(max_length=128)
#     email=models.EmailField(max_length=264, unique= True)

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

AppTwo/forms.py
from django import forms
from django.core import validators
from AppTwo.models import User
from django.contrib.auth.models import User
from AppTwo.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')
# class NewUserForm(forms.ModelForm):
#     class Meta():
#         model = User
#         fields = '__all__'

# # def check_for_z(value):
# #     if value[0].lower() != 'z':
# #         raise forms.ValidationError("Name needs to start with z")
#
# class FormName(forms.Form):
#     # name = forms.CharField(validators=[check_for_z])
#     name = forms.CharField()
#     email = forms.EmailField()
#     verify_email= forms.EmailField(label='Enter your email again:')
#     text = forms.CharField(widget=forms.Textarea)
#     botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])
#
#     def clean(self):
#         all_clean_data = super().clean()
#         email=all_clean_data['email']
#         vmail=all_clean_data['verify_email']
#
#         if email != vmail:
#             raise  forms.ValidationError("make sure emails match!")
#
#
#     # def clean_botcatcher(self):
#     #     botcatcher = self.cleaned_data['botcatcher']
#     #     if len(botcatcher) > 0:
#     #         raise forms.ValidationError("you are a bot!")
#     #     return botcatcher

AppTwo/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from AppTwo.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
# from AppTwo.models import UserForm, UserProfileInfo
# from . import forms
# from AppTwo.forms import NewUserForm
# Create your views here.
# def index(request):
#     return HttpResponse("<em>My Second App</em>")
# def help(request):
#         my_dict = {'insert_me':" I am from views.py !"}
#         return render(request,'AppTwo/help.html',context = my_dict)
def index(request):
        # context_dict = {'text': 'hello world', 'number':100}
        # return render(request,'AppTwo/index.html', context_dict)
        return render(request, 'AppTwo/index.html')

def special(request):
    return HttpResponse("Logged in!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'AppTwo/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')


        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request,'AppTwo/login.html',{})
# def other(request):
#         return render(request,'AppTwo/other.html')
#
# def relative(request):
#         return render(request,'AppTwo/relative_url_templates.html')

# def users(request):
#     form = NewUserForm()
#
#     if request.method == "POST":
#         form = NewUserForm(request.POST)
#
#         if form.is_valid():
#             form.save(commit=True)
#             return index(request)
#         else:
#             print('Form Invalid')
#
#     return render(request, 'AppTwo/users.html', {'form' : form})

# def users(request):
#         user_list = User.objects.order_by('first_name')
#         user_dict = {'users':user_list}
#         return render(request,'AppTwo/users.html',context = user_dict)
#
# def form_name_view(request):
#     form = forms.FormName()
#
#     if request.method ==  'POST':
#         form = forms.FormName(request.POST)
#
#         if form.is_valid():
#             print("VALIDATION SUCCESS!")
#             print("NAME "+form.cleaned_data['name'])
#             print("EMAIL "+form.cleaned_data['email'])
#             print("TEXT "+form.cleaned_data['text'])
#     return render(request, 'AppTwo/form_page.html', {'form':form})

templates/AppTwo/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index'%}">Home Page</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'AppTwo:register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class='navbar-link' href="{% url 'AppTwo:user_login' %}">Login</a></li>
          {% endif %}
        </ul>

      </div>

    </nav>

    <div class="container">

      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend! -->
      {% endblock %}
    </div>
  </body>
</html>

templates/AppTwo/form_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
    <h1>Fill out the form!</h1>
    <div class="container">
      <form  method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>

    </div>
  </body>
</html>

templates/AppTwo/help.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>AppTwo</title>
  </head>
  <body>
    <h1>Hello this is help.html</h1>
    {{ insert_me }}

  </body>
</html>

templates/AppTwo/index.html
<!DOCTYPE html>
{% extends "AppTwo/base.html" %}
  {% block body_block %}
        <!-- <h1>Working!</h1>
        <h2>Go to /users to see the user list</h2>
        <h2>Go to /formpage to fill out the form</h2> -->
      <div class="jumbotron">
        <h1>Recipe Creation Home Page</h1>
      </div>
        <!-- <h1>Welcome!</h1>
        <h1>index.html showing!</h1>
        <h2>Go to /users to sign up!</h2>
        <h1>{{ text|cut:'world' }}</h1>
        <h1>{{ number|add:"99" }}</h1> -->
  {% endblock %}

templates/AppTwo/login.html
<!DOCTYPE html>
{% extends "AppTwo/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'AppTwo:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">

  </form>

</div>
{% endblock %}

templates/AppTwo/other.html
<!DOCTYPE html>

{% extends "AppTwo/base.html"%}
  {% block body_block %}
    <h1>welcome to other!</h1>
    <h2>Inheritance example</h2>
    {% endblock %}

templates/AppTwo/registration.html
<!DOCTYPE html>
{% extends "AppTwo/base.html" %}
{% load static %}
{% block body_block %}
        <!-- <h1>Working!</h1>
        <h2>Go to /users to see the user list</h2>
        <h2>Go to /formpage to fill out the form</h2> -->
      <div class="jumbotron">
        {% if registered %}
          <h1>Thanks for registering!</h1>
        {% else %}
          <h1>Register Here!</h1>
          <h3>Fill out the form:</h3>

          <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">

          </form>
        {% endif %}
      </div>
        <!-- <h1>Welcome!</h1>
        <h1>index.html showing!</h1>
        <h2>Go to /users to sign up!</h2>
        <h1>{{ text|cut:'world' }}</h1>
        <h1>{{ number|add:"99" }}</h1> -->
  {% endblock %}

templates/AppTwo/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>welcome to relative url templates</h1>
    <a href="{% url 'AppTwo:other' %}">the other page</a>
    <a href="{% url 'admin:index' %}">admin</a>
    <a href="{% url 'index' %}">LINK TO INDEX!</a>

  </body>
</html>

templates/AppTwo/users.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Users</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Please sign up here!</h1>
        <form method="POST">
          {{form.as_p}}
          {%csrf_token%}
          <input type="submit" class='btn btn-primary' value="Submit">
        </form>
      </div>

    </div>

    <!-- <h1>Here are your users for AppTwo:</h1>
    {%if users %}
      <ol>
        {% for person in users %}
        <li>User Info</li>
          <ul>
            <li>First Name: {{person.first_naame}}</li>
            <li>Last Name: {{ person.last_name}}</li>
            <li>Email: {{person.email}}</li>
          </ul>
          {% endfor %}
      </ol>

    {% endif %} -->

  </body>
</html>